### ISSUE TITLE
Pre-release checklist

### ISSUE THREAD

**Issue by ColinEberhardt** [ScottLogic/practitioners-guides#2]
Ahead of making these public we should:

- [x] create an internal confluence page that adds additional context and instructions (e.g. how to athour your own report)
- [x] add some light-touch branding
- [x] at the end of each guide, add a link that edits the doc on GitHub to encourage contributions. See for example the [GitHub docs](All GitHub docs are open source. See something that's wrong or unclear? Submit a pull request.)
- [x] add a link to the GitHub project from the left-hand navigation of the GH Pages site

stretch goals

- [x] we have a standard text that describes these books - "About this series - the Scott Logic practitioner's guides are designed to be small practical guides for IT professionals. We draw on our collective experience to tackle topics that we don't feel are addressed elsewhere. Our hope is that these little 'value adds' will help you just as much as they have helped us." - can we template this?
- [x] check / update the description in `_config.yml`, is it being used?
- [ ]
